### ISSUE TITLE
Attention VIRTUAL_HOST dans .env utilisé dans docker-compose

### ISSUE THREAD

**Issue by ypereirareis** [ypereirareis/ypereirareis.github.io#105]
Si utilisation avec docker-compose de `.env` 

```
VIRTUAL_HOST=domain.localhost
LETSENCRYPT_HOST=
LETSENCRYPT_EMAIL=
DATABASE_HOST=
DATABASE_USER=
DATABASE_PASSWORD=
```

et

```
    php:
        image: php:7.1
        env_file:
            - .env
    nginx:
        image: nginx
        environment:
             VIRTUAL_HOST: ${VIRTUAL_HOST}
             LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
             LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
```

Erreur possible : 

```
nginx.1    | 2018/06/07 08:32:39 [error] 147#147: *105 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.19.0.1, server: domain.localhost, request: "POST / HTTP/1.1", upstream: "http://172.19.0.10:9000", host: "domain.localhost", referrer: "http://domain.localhost"
nginx.1    | 2018/06/07 08:32:39 [warn] 147#147: *105 upstream server temporarily disabled while reading response header from upstream, client: 172.19.0.1, server: domain.localhost, request: "POST / HTTP/1.1", upstream: "http://172.19.0.10:9000", host: "domain.localhost", referrer: "http://domain.localhost"
```

Car on a la variable `VIRTUAL_HOST` présente dans le container PHP.
Donc le nginx reverse proxy load balance entre le container NGINX (port 80) et le container PHP-FPM (port 9000) => donc erreur avec le port 9000 sur PHP-FPM
