### ISSUE TITLE
php-fpm truncated logs before 7.3

### ISSUE THREAD

**Issue by ypereirareis** [ypereirareis/ypereirareis.github.io#113]
Configuration for PHP:

```bash
## Named pipe for application logs.
## Trick for bug : https://bugs.php.net/bug.php?id=71880
NAMED_PIPED="/tmp/stdout"

rm -rf "$NAMED_PIPED" || true
mkfifo --mode 600 "${NAMED_PIPED}" || true
chown "$PROJECT_DIR_ID" "${NAMED_PIPED}"
echo  "Named pipe: ($NAMED_PIPED) creation OK"

(tail -q -f ${NAMED_PIPED} >> /proc/self/fd/2 || pkill php-fpm) &

exec "$@" # php-fpm
```

Configuration for monolog: 

```yaml
monolog:
  handlers:
    docker_json:
      type: stream
      path: "/tmp/stdout"
```

for php 7.3 :

fpm pool www.conf:
```
; To remove strings like "[16-Jul-2019 16:24:10] WARNING: [pool www] child 23 said into stderr:" and no more truncated logs
decorate_workers_output = no
```
