### ISSUE TITLE
How to build dynamic services names with expression language

### ISSUE THREAD

**Issue by ypereirareis** [ypereirareis/ypereirareis.github.io#18]
```
parameters:
    acme.debug: true

services:
    acme.provider:
        class: "%acme.provider.class%"
        arguments:
            - "@=parameter('acme.debug') ? service('logger') : null"

```
