### ISSUE TITLE
MongoDbBundle Auththenticated and docker image

### ISSUE THREAD

**Issue by ypereirareis** [ypereirareis/ypereirareis.github.io#24]
```yaml
doctrine_mongodb:
    default_connection: second
    default_document_manager: second
    connections:
        second:
            server: %mongo_second_conn%
            options:
                connect: true
                db: %mongo_second_db%
        first:
            server: %mongo_first_conn%
            options:
                connect: true
                db: %mongo_first_db%
    document_managers:
        second:
            connection: second
            database: %mongo_second_db%
            auto_mapping: true
        first:
            connection: first
            database: %mongo_first_db%
            auto_mapping: true
```

```shell
mongo:
    image: frodenas/mongodb
    command: --nojournal --smallfiles --rest --httpinterface
    environment:
        VIRTUAL_HOST: mongo.dev
        MONGODB_USERNAME: John
        MONGODB_PASSWORD: Doe
        MONGODB_DBNAME: john_doe
    ports:
        - 28017:28017
```
