### ISSUE TITLE
Docker networks made easy

### ISSUE THREAD

**Issue by ypereirareis** [ypereirareis/ypereirareis.github.io#84]
```yml
version: '2'
services:
  kibana:
    image: kibana:5.1.2
    networks:
      - es
      - nginx
networks:
  default:
    external:
      name: sirene-ui
  es:
    external:
     name: sirene-es
  nginx:
    external:
      name: nginx-proxy
```

```yml
version: '2'
services:
  mysql:
    image: mysql:8.0.0
    networks:
      default:
        aliases:
          - db
          - mysql
networks:
  default:
    external:
      name: sirene-data
```

```yml
version: '2'
services:
  php:
    image: zolweb/php7:2.1-alpine
    networks:
      - data
      - default
  es1:
    image: elasticsearch:5.1.2
    networks:
      default:
        aliases:
          - es1
networks:
  default:
    external:
      name: sirene-es
  data:
    external:
     name: sirene-data
```
